# Generated by Django 3.1.5 on 2021-01-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
