# Generated by Django 3.1.5 on 2021-01-15 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Descipción')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('desciption', models.TextField(validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Codigo')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripción')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.area', verbose_name='Área')),
                ('categories', models.ManyToManyField(to='almacen.Category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
