# Generated by Django 3.1.5 on 2021-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Stock Minimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock'),
        ),
    ]
